- name: trigger
  hosts: localhost
  vars:
    Uname: "Administrator"
    Pass: "Nani@1162"
    HostName: "18.119.106.83:8080"
    TokenName: "118adc848a404d4a7e2445d979c76fe58b"
  tasks:
  - name: Queue build
    uri:
      url: "http://{{ 18.119.106.83:8080 }}/job/{{ AWX }}/build?token={{ 118adc848a404d4a7e2445d979c76fe58b }}"
      method: POST
      user: "{{ Uname }}"
      password: "{{ Pass }}"
      force_basic_auth: yes
      status_code: 201
